data_group: weatherbench
name: hongkong_2016
name_short: hongkong_2016
num_variables: null
seasonality: 4
freq: 6h

end_year: 2016
start_year: 1980
splits:
    train: null
    val: null
    test: null
