name: patchtst
model_task: MT
model_params:
  individual: 0
  e_layers: 3
  n_heads: 4
  d_model: 16
  d_ff: 128
  dropout: 0.3
  fc_dropout: 0.3
  head_dropout: 0.0
  patch_len: 16
  stride: 8
  padding_patch: 6
  revin: 1
  affine: 0
  subtract_last: 0
  decomposition: 0
  kernel_size: 4