epochs: 100
accelerator: "gpu"
devices: 1
batch_size: 64
top_c: 64
learning_rate: 0.0002
weight_decay: 0.0
lr_scheduler: "linear_lr"
reverse_eval: True
patience: 5
patience_mode: "min"
patience_delta: 0.0001
monitor_metric: "val_loss"
ckpt_name: "best"


seq_length: 28
pred_length: 7
scale: True

model_params:
  individual: 0

project: "ili"